
import React from 'react';
import { 
  FileText, 
  Layout, 
  UserPlus, 
  LayoutDashboard, 
} from 'lucide-react';
import { TemplateId, ThemeConfig, Language } from './types';

export const NAVIGATION_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/' },
  { id: 'quotes', label: 'Document Library', icon: <FileText size={20} />, path: '/quotes' },
  { id: 'templates', label: 'Design Center', icon: <Layout size={20} />, path: '/templates' },
  { id: 'settings', label: 'Business Profile', icon: <UserPlus size={20} />, path: '/settings' },
];

const BASE_LOGO_CONFIG = {
  logoSize: 100,
  logoOpacity: 100,
  logoAlignment: 'left' as const,
  logoBlendMode: 'normal' as const,
  invertLogo: false,
  logoPosX: 0,
  logoPosY: 0,
};

export const TERMS_PRESETS = {
  en: [
    {
      label: 'Standard (Net 30)',
      text: "1. Validity: This quotation is valid for 14 days from the date of issue.\n2. Payment Terms: Net 30 days from the invoice date.\n3. Currency: All prices are in the currency specified above.\n4. Confidentiality: Both parties agree to keep all pricing and technical details confidential."
    },
    {
      label: 'Service / Maintenance',
      text: "1. Scope: Services will be performed during standard business hours (Mon-Fri, 9am-5pm).\n2. Exclusions: Hardware replacement costs are not included unless specified.\n3. Payment: 50% upfront, 50% upon completion.\n4. Liability: Our liability is limited to the total amount of this quotation."
    },
    {
      label: 'Upfront Payment',
      text: "1. Payment: 100% advance payment required before project initiation.\n2. Delivery: Delivery timeline starts after the receipt of payment.\n3. Refunds: This service is non-refundable once work has commenced."
    },
    {
      label: 'Simple / Friendly',
      text: "Thank you for your business!\n- Please confirm this quote via email to proceed.\n- Payment is due within 14 days of invoice receipt.\n- Feel free to contact us if you have any questions."
    }
  ],
  ko: [
    {
      label: '표준 용역 계약 (일반)',
      text: "1. 유효기간: 본 견적서는 발행일로부터 14일간 유효합니다.\n2. 결제조건: 세금계산서 발행 후 15일 이내 현금 결제를 원칙으로 합니다.\n3. 부가세: 별도 표기가 없는 한, 모든 금액은 부가세(VAT) 별도입니다.\n4. 비밀유지: 양사는 본 견적을 통해 알게 된 상대방의 정보를 제3자에게 누설하지 않습니다."
    },
    {
      label: '개발 및 유지보수',
      text: "1. 착수금: 계약 금액의 50% 입금 확인 후 프로젝트를 착수합니다.\n2. 잔금: 최종 검수 완료 후 7일 이내 지급합니다.\n3. 하자보수: 검수 완료일로부터 1개월간 무상 하자보수를 지원합니다 (기능 추가 제외).\n4. 소유권: 결과물에 대한 소유권은 잔금 완납 시 발주사에 귀속됩니다."
    },
    {
      label: '선결제 / 물품 공급',
      text: "1. 결제조건: 100% 선결제 조건입니다.\n2. 납기: 입금 확인 후 영업일 기준 3일 이내 발송됩니다.\n3. 반품/교환: 제품 포장 훼손 시 교환 및 환불이 불가할 수 있습니다."
    },
    {
      label: '간이 영수 / 일반',
      text: "이용해 주셔서 감사합니다.\n- 위 금액은 부가세(VAT) 별도 금액입니다.\n- 진행을 원하시면 본 메일로 회신 또는 날인된 사본을 보내주세요.\n- 문의사항: 02-0000-0000"
    }
  ]
};

export const THEME_PRESETS: Record<TemplateId, ThemeConfig> = {
  standard: {
    primaryColor: '#0f172a',
    secondaryColor: '#64748b',
    paperColor: '#ffffff',
    fontFamily: 'sans',
    borderRadius: 'none',
    headerLayout: 'split',
    tableStyle: 'bordered',
    accentAlpha: 0.05,
    showWatermark: false,
    paperPadding: 'normal',
    ...BASE_LOGO_CONFIG
  },
  modern: {
    primaryColor: '#4f46e5',
    secondaryColor: '#818cf8',
    paperColor: '#ffffff',
    fontFamily: 'montserrat',
    borderRadius: 'large',
    headerLayout: 'split',
    tableStyle: 'minimal',
    accentAlpha: 0.1,
    showWatermark: false,
    paperPadding: 'normal',
    ...BASE_LOGO_CONFIG
  },
  minimal: {
    primaryColor: '#1e293b',
    secondaryColor: '#94a3b8',
    paperColor: '#ffffff',
    fontFamily: 'noto',
    borderRadius: 'none',
    headerLayout: 'centered',
    tableStyle: 'minimal',
    accentAlpha: 0,
    showWatermark: false,
    paperPadding: 'wide',
    ...BASE_LOGO_CONFIG,
    logoAlignment: 'center'
  },
  bold: {
    primaryColor: '#000000',
    secondaryColor: '#404040',
    paperColor: '#ffffff',
    fontFamily: 'mono',
    borderRadius: 'none',
    headerLayout: 'banner',
    tableStyle: 'grid',
    accentAlpha: 0.15,
    showWatermark: true,
    paperPadding: 'normal',
    ...BASE_LOGO_CONFIG
  },
  elegant: {
    primaryColor: '#78350f',
    secondaryColor: '#b45309',
    paperColor: '#fffaf0',
    fontFamily: 'playfair',
    borderRadius: 'none',
    headerLayout: 'centered',
    tableStyle: 'minimal',
    accentAlpha: 0.03,
    showWatermark: true,
    paperPadding: 'wide',
    ...BASE_LOGO_CONFIG,
    logoAlignment: 'center'
  },
  tech: {
    primaryColor: '#0ea5e9',
    secondaryColor: '#38bdf8',
    paperColor: '#ffffff',
    fontFamily: 'mono',
    borderRadius: 'medium',
    headerLayout: 'clean',
    tableStyle: 'bordered',
    accentAlpha: 0.08,
    showWatermark: false,
    paperPadding: 'compact',
    ...BASE_LOGO_CONFIG
  },
  playful: {
    primaryColor: '#ec4899',
    secondaryColor: '#f472b6',
    paperColor: '#ffffff',
    fontFamily: 'sans',
    borderRadius: 'full',
    headerLayout: 'split',
    tableStyle: 'striped',
    accentAlpha: 0.12,
    showWatermark: false,
    paperPadding: 'normal',
    ...BASE_LOGO_CONFIG
  },
  eco: {
    primaryColor: '#166534',
    secondaryColor: '#22c55e',
    paperColor: '#f0fdf4',
    fontFamily: 'roboto-slab',
    borderRadius: 'medium',
    headerLayout: 'split',
    tableStyle: 'minimal',
    accentAlpha: 0.05,
    showWatermark: false,
    paperPadding: 'normal',
    ...BASE_LOGO_CONFIG
  },
  midnight: {
    primaryColor: '#818cf8',
    secondaryColor: '#94a3b8',
    paperColor: '#0f172a',
    fontFamily: 'sans',
    borderRadius: 'large',
    headerLayout: 'split',
    tableStyle: 'minimal',
    accentAlpha: 0.2,
    showWatermark: true,
    paperPadding: 'normal',
    ...BASE_LOGO_CONFIG,
    invertLogo: true
  },
  brutalist: {
    primaryColor: '#facc15',
    secondaryColor: '#000000',
    paperColor: '#ffffff',
    fontFamily: 'mono',
    borderRadius: 'none',
    headerLayout: 'banner',
    tableStyle: 'grid',
    accentAlpha: 1,
    showWatermark: false,
    paperPadding: 'normal',
    ...BASE_LOGO_CONFIG
  },
  vogue: {
    primaryColor: '#000000',
    secondaryColor: '#d1d5db',
    paperColor: '#ffffff',
    fontFamily: 'playfair',
    borderRadius: 'none',
    headerLayout: 'centered',
    tableStyle: 'minimal',
    accentAlpha: 0,
    showWatermark: false,
    paperPadding: 'wide',
    ...BASE_LOGO_CONFIG,
    logoAlignment: 'center'
  },
  organic: {
    primaryColor: '#4d7c0f',
    secondaryColor: '#a3e635',
    paperColor: '#fef3c7',
    fontFamily: 'roboto-slab',
    borderRadius: 'large',
    headerLayout: 'split',
    tableStyle: 'minimal',
    accentAlpha: 0.05,
    showWatermark: false,
    paperPadding: 'normal',
    ...BASE_LOGO_CONFIG
  }
};

export const AVAILABLE_TEMPLATES: { id: TemplateId; name: string; tags: string[] }[] = [
  { id: 'standard', name: 'Standard Professional', tags: ['Corporate', 'Clean'] },
  { id: 'modern', name: 'Modern Indigo', tags: ['Startup', 'Creative'] },
  { id: 'minimal', name: 'Pure Minimalist', tags: ['Sleek', 'Quiet'] },
  { id: 'bold', name: 'High Contrast Bold', tags: ['Impact', 'Strong'] },
  { id: 'elegant', name: 'Elegant Script', tags: ['Luxury', 'Classic'] },
  { id: 'tech', name: 'Cyber Technical', tags: ['IT', 'Modern'] },
  { id: 'playful', name: 'Playful Pink', tags: ['Vibrant', 'Fun'] },
  { id: 'eco', name: 'Organic Green', tags: ['Eco', 'Nature'] },
  { id: 'midnight', name: 'Deep Midnight', tags: ['Dark Mode', 'Premium'] },
  { id: 'brutalist', name: 'Neo Brutalist', tags: ['Art', 'Raw'] },
  { id: 'vogue', name: 'Vogue Fashion', tags: ['Style', 'High-end'] },
  { id: 'organic', name: 'Warm Organic', tags: ['Handcrafted', 'Warm'] },
];

export const UI_STRINGS = {
  en: {
    // Layout
    dashboard: 'Dashboard',
    quotes: 'Document Library',
    templates: 'Design Center',
    settings: 'Business Profile',
    quickCreate: 'Quick Create',
    restartGuide: 'Guide',

    serviceFooter: 'QuoteTonic by NTK. Authorized use only.',
    documentEditor: 'Document Editor',

    // Dashboard
    workspaceSub: 'Your command center for sales documents.',
    welcomeBack: 'Welcome Back',
    startNewProject: 'Start a New Project',
    startNewProjectDesc: 'Create professional quotes in seconds.',
    resumeDraft: 'Resume Draft',
    lastEdited: 'Last edited',
    continue: 'Continue',
    newQuote: 'New Document',
    qa_new: 'Create Empty',
    qa_copy: 'Copy Last',
    qa_copy_desc: 'Duplicate recent doc',
    standardTemplate: 'Standard Template',
    recentQuotes: 'Recent Documents',
    filterAll: 'See All',
    totalAmount: 'Total Value',
    noData: 'No Quotes Found',
    tutorialWelcomeDesc: 'Create your first quote to get started.',
    
    // Status
    status: 'Status',
    status_Draft: 'Draft',
    status_Finalized: 'Sent',
    status_Won: 'Won',
    status_Lost: 'Lost',
    markAsWon: 'Mark as Won',
    markAsLost: 'Mark as Lost',

    // Editor & Preview
    headerPreview: 'Design Preview',
    viewFit: 'Fit to Screen',
    viewScroll: 'Scroll View',
    back: 'Back',
    saveAll: 'Save',
    preview: 'Preview',
    generate: 'Generate',
    sendEmail: 'Send Email',
    copyText: 'Copy Text',
    copyTextDesc: 'Copy Summary',
    copySuccess: 'Copied!',
    aiGenerationHint: 'Bulk import or add items below...',
    aiPromptPlaceholder: 'Search or add items...',
    bulkImport: 'Bulk Import',
    bulkImportDesc: 'Paste rows from Excel (Description | Qty | Price)',
    pasteAreaPlaceholder: 'Paste Excel data here...',
    import: 'Import',
    addItem: 'Add Item',
    cloneItem: 'Clone',
    delete: 'Delete',
    docTypeQuote: 'Quotation',
    docTypeInvoice: 'Invoice',
    pressEnter: 'Press Enter',
    livePreview: 'Live Preview',
    
    // Quote Fields
    client: 'Client',
    clientPlaceholder: 'Client Name / Company',
    date: 'Date',
    issueDate: 'Issue Date',
    expiryDate: 'Expiry',
    dueDate: 'Due Date',
    currency: 'Currency',
    lineItems: 'Line Items',
    description: 'Description',
    descPlaceholder: 'Item description...',
    quantity: 'Qty',
    unitPrice: 'Price',
    discount: 'Discount',
    tax: 'Tax',
    terms: 'Terms & Conditions',
    termsPlaceholder: 'Enter custom terms or select a preset...',
    loadPreset: 'Load Preset',
    footerNotes: 'Footer Notes',
    noteTax: 'Notes',
    subtotal: 'Subtotal',
    grandTotal: 'Total',
    
    // Document Paper Labels (The actual text on the PDF)
    quotationTitle: 'QUOTATION',
    invoiceTitle: 'INVOICE',
    billTo: 'BILL TO',
    schedule: 'SCHEDULE',
    representativeLabel: 'REPRESENTATIVE',
    companyIdentity: 'IDENTITY', // Business License / Reg Info header
    regNo: 'REG NO.',
    bankInfo: 'BANK',
    itemDescriptionHeader: 'DESCRIPTION',
    qtyHeader: 'QTY',
    priceHeader: 'PRICE',
    totalHeader: 'AMOUNT',
    signature: 'SIGNATURE',
    
    // Template Customizer
    themePresets: 'Presets',
    typography: 'Typography',
    primaryColor: 'Brand Color',
    customColor: 'Custom',
    layoutStructure: 'Layout',
    headerSplit: 'Split',
    headerCentered: 'Center',
    headerBanner: 'Banner',
    headerClean: 'Clean',
    logoBranding: 'Logo & Branding',
    logoSize: 'Size',
    logoOpacity: 'Opacity',
    logoPosition: 'Position',
    invertLogo: 'Invert',
    blendMode: 'Blend Mode',
    blendNormal: 'Normal',
    blendMultiply: 'Multiply (Remove White)',
    blendScreen: 'Screen (Remove Black)',
    resetPosition: 'Reset',
    dragHint: 'Drag to move • Drag corner to resize',
    borderRadius: 'Corner Radius',
    showWatermark: 'Watermark',
    patternBackground: 'Pattern Background',
    useThisTheme: 'Use This Theme',
    saveGlobalDefault: 'Save as Default',
    saveSuccess: 'Settings Saved',
    
    // Settings
    uploadLogo: 'Upload Logo',
    uploadTip: 'PNG, JPG (Transparent BG recommended)',
    logoSettingsMoved: 'Visit Design Center to adjust position & style.',
    companyName: 'Company Name',
    representative: 'Representative',
    address: 'Address',
    contactInfo: 'Contact Info',
    companyEmail: 'Email',
    companyPhone: 'Phone',
    website: 'Website',
    financialDefaults: 'Financial Defaults',
    docPrefix: 'Prefix',
    nextNumber: 'Next Number',
    signatureLab: 'Signature Lab',
    drawSignature: 'Draw',
    typeSignature: 'Type',
    uploadSeal: 'Upload',
    drawSignatureDesc: 'Draw your signature here',
    initialPlaceholder: 'Initials',
    generateWithAi: 'Generate',
    applySignature: 'Apply Signature',
    selectImage: 'Select Image',
    colorBlack: 'Black',
    colorBlue: 'Blue',
    colorRed: 'Red',
    saving: 'Saving...',
    docPrefixPlaceholder: 'QT-',
    
    // Common
    create: 'Create',
    cancel: 'Cancel',
    actions: 'Actions',
    deleteConfirm: 'Are you sure you want to delete this document?',
    copySuffix: '(Copy)',
    searchPlaceholder: 'Search documents...',
    noSearchResults: 'No documents found matching your search.',
    pdfError: 'PDF generation failed. Please try again.',
    aiError: 'AI processing failed. Please try again.',
    emptyState: 'Empty',
    tutorialTitle: 'Onboarding Mission',
    stepLabel: 'Step',
    
    // Template Modal
    templateSelect: 'Select Template',
    choosePresetLabel: 'Choose a design style for your document.',
    doubleClickSelect: 'Double-click to Select',
    greatChoice: 'Great choice!',

    // Guide
    guide_welcome_title: 'Welcome to QuoteTonic',
    guide_welcome_desc: 'Let us guide you through creating your first professional quotation in minutes.',
    guide_start_btn: 'Start Tour',
    guide_skip_btn: 'Skip',
    guide_next: 'Next',
    guide_prev: 'Back',
    guide_finish: 'Finish',
    guide_step1_title: 'Start Project',
    guide_step1_desc: 'Click "New Document" to begin your first quote.',
    guide_step2_title: 'Select Template',
    guide_step2_desc: 'Choose "Standard Professional" to get started quickly.',
    guide_step3_title: 'Client Information',
    guide_step3_desc: 'Type the client name here. Press Enter to move next.',
    
    // NEW STEP
    guide_step4_title: 'Document Branding',
    guide_step4_desc: 'Set your logo and colors to make the document yours.',
    
    guide_step5_title: 'Line Items',
    guide_step5_desc: 'Edit or add detailed service or product items manually.',
    guide_step6_title: 'Preview',
    guide_step6_desc: 'Click here to see how your document looks.',
    guide_step7_title: 'Finalize & Export',
    guide_step7_desc: 'Save to library, or export as PDF / Send Email immediately.',
    guide_step8_title: 'Library Access',
    guide_step8_desc: 'Navigate to "Document Library" to see your saved work.',
    guide_step9_title: 'Organize',
    guide_step9_desc: 'Filter documents by status (Draft, Won, Lost).',
    guide_step10_title: 'Design Center',
    guide_step10_desc: 'Go to "Design Center" to customize the look.',
    guide_step11_title: 'Brand Colors',
    guide_step11_desc: 'Select a primary color that matches your brand.',
    guide_step12_title: 'Profile Settings',
    guide_step12_desc: 'Go to "Business Profile" to set up your company.',
    guide_step13_title: 'Company Logo',
    guide_step13_desc: 'Upload your official company logo here.',
    guide_step14_title: 'Signature Lab',
    guide_step14_desc: 'Create a digital signature for your documents.',
    guide_step15_title: 'Draw Signature',
    guide_step15_desc: 'Draw your signature on the canvas.',
    guide_step16_title: 'Save Profile',
    guide_step16_desc: 'Save all your business settings.',
    guide_step17_title: 'You are ready!',
    guide_step17_desc: 'Now you can create unlimited professional documents.',
  },
  ko: {
    // Layout
    dashboard: '대시보드',
    quotes: '문서 보관함',
    templates: '디자인 센터',
    settings: '비즈니스 프로필',
    quickCreate: '빠른 작성',
    restartGuide: '가이드',

    serviceFooter: 'QuoteTonic by NTK. 무단 전재 금지.',
    documentEditor: '문서 에디터',

    // Dashboard
    workspaceSub: '영업 문서를 효율적으로 관리하세요.',
    welcomeBack: '반갑습니다',
    startNewProject: '새 프로젝트 시작',
    startNewProjectDesc: '전문적인 견적서를 단 몇 초 만에 작성하세요.',
    resumeDraft: '작성 중인 문서',
    lastEdited: '최종 수정',
    continue: '이어서 작성',
    newQuote: '새 문서 작성',
    qa_new: '빈 문서 생성',
    qa_copy: '최근 문서 복사',
    qa_copy_desc: '최근 내용을 그대로 복제',
    standardTemplate: '표준 템플릿',
    recentQuotes: '최근 문서',
    filterAll: '전체 보기',
    totalAmount: '총 공급가액',
    noData: '문서가 없습니다',
    tutorialWelcomeDesc: '첫 번째 견적서를 작성하여 시작해보세요.',
    
    // Status
    status: '상태',
    status_Draft: '작성 중',
    status_Finalized: '발송 완료',
    status_Won: '수주 성공',
    status_Lost: '미수주',
    markAsWon: '수주 처리',
    markAsLost: '미수주 처리',

    // Editor & Preview
    headerPreview: '디자인 미리보기',
    viewFit: '화면 맞춤',
    viewScroll: '스크롤 보기',
    back: '뒤로',
    saveAll: '저장',
    preview: '미리보기',
    generate: '생성',
    sendEmail: '이메일 발송',
    copyText: '텍스트 복사',
    copyTextDesc: '요약 내용 복사',
    copySuccess: '복사됨!',
    aiGenerationHint: '항목을 직접 추가하거나 대량으로 가져오세요...',
    aiPromptPlaceholder: '항목을 검색하거나 추가하세요...',
    bulkImport: '엑셀 붙여넣기',
    bulkImportDesc: '엑셀 행을 복사해서 붙여넣으세요 (품목명 | 수량 | 단가)',
    pasteAreaPlaceholder: '엑셀 데이터를 여기에 붙여넣으세요...',
    import: '가져오기',
    addItem: '항목 추가',
    cloneItem: '복제',
    delete: '삭제',
    docTypeQuote: '견적서 (Quotation)',
    docTypeInvoice: '청구서 (Invoice)',
    pressEnter: 'Enter 키',
    livePreview: '실시간 미리보기',
    
    // Quote Fields
    client: '수신처 (고객사)',
    clientPlaceholder: '고객사명 또는 담당자',
    date: '발행일',
    issueDate: '발행일',
    expiryDate: '유효기간',
    dueDate: '납기일/만기일',
    currency: '통화',
    lineItems: '상세 항목',
    description: '품목명 / 적요',
    descPlaceholder: '항목 내용을 입력하세요',
    quantity: '수량',
    unitPrice: '단가',
    discount: '할인',
    tax: '세율 (VAT)',
    terms: '이용 약관 및 특약',
    termsPlaceholder: '약관을 입력하거나 프리셋을 불러오세요...',
    loadPreset: '프리셋 불러오기',
    footerNotes: '푸터 메모',
    noteTax: '비고',
    subtotal: '공급가액',
    grandTotal: '합계 금액',
    
    // Document Paper Labels (The actual text on the PDF)
    quotationTitle: '견 적 서',
    invoiceTitle: '청 구 서',
    billTo: '수신 (청구처)',
    schedule: '일정 및 기한',
    representativeLabel: '대표자',
    companyIdentity: '사업자 정보',
    regNo: '등록번호',
    bankInfo: '계좌정보',
    itemDescriptionHeader: '품목명',
    qtyHeader: '수량',
    priceHeader: '단가',
    totalHeader: '공급가액',
    signature: '서명',
    
    // Template Customizer
    themePresets: '테마 프리셋',
    typography: '폰트 스타일',
    primaryColor: '브랜드 컬러',
    customColor: '직접 선택',
    layoutStructure: '헤더 레이아웃',
    headerSplit: '분할형',
    headerCentered: '중앙 정렬',
    headerBanner: '배너형',
    headerClean: '심플형',
    logoBranding: '로고 스타일',
    logoSize: '크기',
    logoOpacity: '투명도',
    logoPosition: '위치',
    invertLogo: '색상 반전',
    blendMode: '배경 혼합',
    blendNormal: '표준',
    blendMultiply: '투명화 (흰색 제거)',
    blendScreen: '투명화 (검은색 제거)',
    resetPosition: '위치 초기화',
    dragHint: '드래그하여 이동 • 모서리로 크기 조절',
    borderRadius: '모서리 둥글기',
    showWatermark: '워터마크 패턴',
    patternBackground: '배경 패턴 표시',
    useThisTheme: '이 테마 적용하기',
    saveGlobalDefault: '기본값으로 저장',
    saveSuccess: '설정이 저장되었습니다.',
    
    // Settings
    uploadLogo: '로고 업로드',
    uploadTip: 'PNG, JPG (투명 배경 권장)',
    logoSettingsMoved: '디자인 센터에서 로고의 위치와 스타일을 정교하게 조정하세요.',
    companyName: '회사명',
    representative: '대표자명',
    address: '주소',
    contactInfo: '연락처 정보',
    companyEmail: '이메일',
    companyPhone: '전화번호',
    website: '웹사이트',
    financialDefaults: '금융 및 문서 설정',
    docPrefix: '문서 번호 접두어',
    nextNumber: '다음 번호',
    signatureLab: '서명 만들기',
    drawSignature: '그리기',
    typeSignature: '입력',
    uploadSeal: '업로드',
    drawSignatureDesc: '이곳에 서명을 그리세요',
    initialPlaceholder: '이니셜 입력',
    generateWithAi: '생성',
    applySignature: '서명 적용',
    selectImage: '이미지 선택',
    colorBlack: '검정',
    colorBlue: '파랑',
    colorRed: '빨강',
    saving: '저장 중...',
    
    // Common
    create: '생성',
    cancel: '취소',
    actions: '동작',
    deleteConfirm: '정말 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
    copySuffix: '(복사본)',
    searchPlaceholder: '문서 검색...',
    noSearchResults: '검색 결과가 없습니다.',
    pdfError: 'PDF 생성 중 문제가 발생했습니다. 다시 시도해주세요.',
    aiError: 'AI 처리에 실패했습니다. 다시 시도해주세요.',
    emptyState: '비어있음',
    tutorialTitle: '튜토리얼 미션',
    stepLabel: '단계',
    
    // Template Modal
    templateSelect: '템플릿 선택',
    choosePresetLabel: '문서의 분위기에 맞는 디자인을 선택하세요.',
    doubleClickSelect: '더블 클릭하여 선택',
    greatChoice: '좋은 선택입니다!',
    docPrefixPlaceholder: 'QT-',

    // Guide
    guide_welcome_title: 'QuoteTonic 시작하기',
    guide_welcome_desc: '빠르고 간편하게 전문적인 견적서를 만드는 방법을 안내해 드릴게요.',
    guide_start_btn: '가이드 시작',
    guide_skip_btn: '건너뛰기',
    guide_next: '다음',
    guide_prev: '이전',
    guide_finish: '완료',
    guide_step1_title: '새 문서 작성',
    guide_step1_desc: '대시보드의 "새 문서 작성" 버튼을 클릭하여 시작하세요.',
    guide_step2_title: '디자인 선택',
    guide_step2_desc: '가장 인기있는 "표준 템플릿"을 선택해보세요.',
    guide_step3_title: '수신처 입력',
    guide_step3_desc: '고객사명을 입력하세요. Enter를 누르면 다음으로 이동합니다.',
    
    // NEW STEP
    guide_step4_title: '브랜드 설정',
    guide_step4_desc: '로고와 브랜드 색상을 설정하여 신뢰감을 더하세요.',
    
    guide_step5_title: '항목 작성',
    guide_step5_desc: '제공할 서비스나 제품명을 직접 입력하거나 수정하세요.',
    guide_step6_title: '미리보기',
    guide_step6_desc: '우측 상단의 미리보기 버튼을 눌러보세요.',
    guide_step7_title: '저장 및 내보내기',
    guide_step7_desc: '문서를 저장하고, PDF로 받거나 이메일로 바로 보낼 수 있습니다.',
    guide_step8_title: '문서 보관함',
    guide_step8_desc: '왼쪽 사이드바의 "문서 보관함" 메뉴로 이동하세요.',
    guide_step9_title: '필터링',
    guide_step9_desc: '작성 중, 발송 완료 등 상태별로 모아볼 수 있습니다.',
    guide_step10_title: '디자인 센터',
    guide_step10_desc: '"디자인 센터" 메뉴에서 문서 스타일을 수정해보세요.',
    guide_step11_title: '브랜드 컬러',
    guide_step11_desc: '우리 회사의 브랜드 컬러를 지정하세요.',
    guide_step12_title: '프로필 설정',
    guide_step12_desc: '"비즈니스 프로필" 메뉴로 이동하여 회사 정보를 입력하세요.',
    guide_step13_title: '로고 업로드',
    guide_step13_desc: '회사 로고 이미지를 이곳에 업로드하세요.',
    guide_step14_title: '전자 서명',
    guide_step14_desc: '문서에 사용할 직인이나 서명을 만드세요.',
    guide_step15_title: '서명 그리기',
    guide_step15_desc: '마우스로 서명을 직접 그려보세요.',
    guide_step16_title: '설정 저장',
    guide_step16_desc: '입력한 모든 설정을 저장합니다.',
    guide_step17_title: '준비 완료!',
    guide_step17_desc: '이제 QuoteTonic으로 멋진 견적서를 만들어보세요!',
  }
};
